### ISSUE TITLE
Does not work on CrazyGames.com and other game portals

### ISSUE THREAD

**Issue by bergice** [nisovin/godot-coi-serviceworker#1]
We've tried uploading zipped builds and iframes using this workaround to CrazyGames.com, but it does not seem to work.

![image](https://github.com/gzuidhof/coi-serviceworker/assets/541886/42c769d8-cbac-4427-a582-127af2a08e15)

Is there some restriction with this workaround we're not aware of?

**Comment by nisovin** [comment]
If there is a cross-origin iframe, I don't think this work-around will work unless the containing page has the right configuration. This addon will probably only work if the game is not embedded.

**Comment by FartFish** [comment]
Did you find a solution to this when closing the issue, or did you mark it as closed because there is no solution?
