### ISSUE TITLE
doesnt work in firefox private browsing

### ISSUE THREAD

**Issue by apia46** [nisovin/godot-coi-serviceworker#4]
that is all i know. sorry

**Comment by Beeka274** [comment]
this seems to be a known issue; are there any workarounds?

**Comment by nisovin** [comment]
As far as I can tell, Firefox disables service workers entirely in private browsing. So no, there's no way to work around this. If you want to have a game work in private browsing, you would need to set the headers properly. Or you could use the new 4.3 version that doesn't require threads.
